apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: app
type: Opaque
data:
  DATABASE_URL: bXlzcWw6Ly91c2VyOnBhc3N3b3JkQGRiLXNlcnZlcjoxMjM0L2RhdGFiYXNl
  JWT_SECRET: c3VwZXJfc2VjcmV0X2tleQ==
